apiVersion: v1
kind: Secret
metadata:
  name: flink-storage-secret
type: Opaque
data:
  azurestorageaccountkey: U1YzOXJHb2RwcGhvS0RMYkhHWk8rKzdqQ3hKOFdBcGxwY056ekhoZG40NGVPY252Uk9yZDFJR1lpV3FJUTlnK0VyUkxVN09yLzVQS0dDUm1oSnNQSnc9PQ==