apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-configmap
  namespace: default
subjects:
- kind: ServiceAccount
  name: flink-service-account
  namespace: default
roleRef:
  kind: Role
  name: role-for-configmap
  apiGroup: rbac.authorization.k8s.io